name: test

on:
  pull_request:
    branches: 
      - main
      - dev

jobs:
  test_versions:
    name: testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
      
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Deps
        run: | 
          pip install .[dev]
          playwright install
          playwright install-deps

      - name: Type Check
        run: |
          pyright src/struct_strm

      - name: Test
        run: |
          pytest

